name: Run Colab Notebook Every 5 Hours

on:
  schedule:
    - cron: "0 */5 * * *"  # Automatically runs every 5 hours
  workflow_dispatch:  # Allows manual triggering from the GitHub Actions UI

jobs:
  run_colab_notebook:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install necessary packages
      run: |
        pip install gdown google-auth google-auth-oauthlib google-auth-httplib2 jupyter nbconvert gspread

    - name: Set up Google credentials
      env:
        GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      run: |
        # Write the credentials JSON from the secret to a file
        echo "${GOOGLE_APPLICATION_CREDENTIALS_JSON}" > $HOME/credentials.json
        export GOOGLE_APPLICATION_CREDENTIALS=$HOME/credentials.json

    - name: Run the Colab notebook
      run: |
        # Ensure the necessary libraries are installed
        python -m pip install --upgrade pip

        # Execute the notebook
        jupyter nbconvert --execute --inplace --allow-errors --to notebook KWANZA_TUKULE_CASE_STUDY.ipynb

    - name: Commit and push the executed notebook (optional)
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add KWANZA_TUKULE_CASE_STUDY.ipynb
        git commit -m "Run notebook and update output"
        git push
